default_platform(:ios)

platform :ios do
  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  lane :beta do
    bootstrap
    increment_build_number({
      build_number: latest_testflight_build_number + 1
    })
    gym(
      scheme: "Bitrise-iOS",
      configuration: "Release"
    )
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    bootstrap
    increment_build_number({
      build_number: latest_testflight_build_number + 1
    })
    gym(
      scheme: "Bitrise-iOS",
      configuration: "Release"
    )
  end

  private_lane :bootstrap do
    carthage(
      command: "bootstrap",
      platform: "iOS",
      cache_builds: true
    )
  end
end
